---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  entityOperator:
    tlsSidecar:
      livenessProbe:
        initialDelaySeconds: 20
        timeoutSeconds: 5
      readinessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 50m
          memory: 100M
        requests:
          cpu: 50m
          memory: 100M
    topicOperator:
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 250m
          memory: 250M
    userOperator:
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 250m
          memory: 250M
        requests:
          cpu: 150m
          memory: 150M
  kafka:
    tlsSidecar:
      livenessProbe:
        initialDelaySeconds: 20
        timeoutSeconds: 5
      readinessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 50m
          memory: 50M
    config:
      log.message.format.version: 2.3
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
    metrics:
      lowercaseOutputName: true
      rules:
        - labels:
            clientId: $3
            partition: $5
            topic: $4
          name: kafka_server_$1_$2
          pattern: >-
            kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+),
            partition=(.*)><>Value
          type: GAUGE
        - labels:
            broker: '$4:$5'
            clientId: $3
          name: kafka_server_$1_$2
          pattern: >-
            kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+),
            brokerPort=(.+)><>Value
          type: GAUGE
        - name: kafka_$1_$2_$3_percent
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate'
          type: GAUGE
        - name: kafka_$1_$2_$3_percent
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value'
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_percent
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value'
          type: GAUGE
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3_total
          pattern: >-
            kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+),
            (.+)=(.+)><>Count
          type: COUNTER
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_total
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count'
          type: COUNTER
        - name: kafka_$1_$2_$3_total
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count'
          type: COUNTER
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value'
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value'
          type: GAUGE
        - name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Value'
          type: GAUGE
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3_count
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count'
          type: COUNTER
        - labels:
            $4: $5
            $6: $7
            quantile: 0.$8
          name: kafka_$1_$2_$3
          pattern: >-
            kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*),
            (.+)=(.+)><>(\d+)thPercentile
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_count
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count'
          type: COUNTER
        - labels:
            $4: $5
            quantile: 0.$6
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile'
          type: GAUGE
        - name: kafka_$1_$2_$3_count
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Count'
          type: COUNTER
        - labels:
            quantile: 0.$4
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile'
          type: GAUGE
    resources:
      limits:
        cpu: '1'
        memory: 2G
      requests:
        cpu: 300m
        memory: 500M
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 45
      timeoutSeconds: 5
    version: 2.3.0
    storage:
      deleteClaim: true
      size: 2Gi
      type: persistent-claim
    replicas: 3
    jvmOptions:
      gcLoggingEnabled: false
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
    metrics:
      lowercaseOutputName: true
      rules:
        - name: zookeeper_$2
          pattern: org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+)><>(\w+)
        - labels:
            replicaId: $2
          name: zookeeper_$3
          pattern: >-
            org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+),
            name1=replica.(\d+)><>(\w+)
        - labels:
            memberType: $3
            replicaId: $2
          name: zookeeper_$4
          pattern: >-
            org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+),
            name1=replica.(\d+), name2=(\w+)><>(\w+)
        - labels:
            memberType: $3
            replicaId: $2
          name: zookeeper_$4_$5
          pattern: >-
            org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+),
            name1=replica.(\d+), name2=(\w+), name3=(\w+)><>(\w+)
        - name: zookeeper_$2
          pattern: org.apache.ZooKeeperService<name0=StandaloneServer_port(\d+)><>(\w+)
        - name: zookeeper_$2_$3
          pattern: >-
            org.apache.ZooKeeperService<name0=StandaloneServer_port(\d+),
            name1=(InMemoryDataTree)><>(\w+)
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 250M
      requests:
        cpu: 100m
        memory: 100M
    storage:
      deleteClaim: true
      size: 1Gi
      type: persistent-claim
    tlsSidecar:
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        initialDelaySeconds: 20
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 50m
          memory: 50M
